// Gameboard object for gameboard-related functionality
const Gameboard = (function () {
    // Board variables
    const gameBoard = [];
    const boardLength = 9;
    let markersPlaced = 0;
    // Markers
    const markerX = "X";
    const markerO = "O";
    // Players (hard-coded for now)
    const player1 = Player("Nour", markerX);
    const player2 = Player("Abdullah", markerO);
    return {
        // Reset all values in array
        resetBoard: () => {
            for (let i = 0; i < boardLength; i++) {
                if (!(gameBoard[i] === 0)) {
                    gameBoard[i] = 0;
                }
            }
        },
        // Log all board values 9x9
        logBoard: () => {
            let outputValue = "";
            for (let i = 0; i < boardLength; i++) {
                outputValue += ` ${gameBoard[i]} `;
                if (i === 2 || i === 5 || i === 8) {
                    outputValue += "\n";
                }
            }
            return outputValue;
        },
        // Log board index to prevent empty values
        logBoardIndex: (boardIndex) => {
            const boardValue = gameBoard[boardIndex];
            return boardValue;
        },
        // Logic to insert marker in array, array termination, and array iteration with edge cases
        insertMarker: (index) => {
            const playerOneMarker = player1.getMarker();
            const playerTwoMarker = player2.getMarker();
            if (gameBoard[index] === 0 && index < boardLength && index >= 0) {
                if (markersPlaced % 2 == 0) {
                    gameBoard[index] = playerOneMarker;
                    markersPlaced += 1;
                    Gameboard.lastPlayed(playerOneMarker);
                } else {
                    gameBoard[index] = playerTwoMarker;
                    markersPlaced += 1;
                    Gameboard.lastPlayed(playerTwoMarker);
                }
            }
        },

        checkResults: () => {
            if ( // Logic by me, conditions generated by AI to fasten code typing.
                (gameBoard[0] !== 0 &&
                    gameBoard[1] !== 0 &&
                    gameBoard[2] !== 0 &&
                    gameBoard[0] === gameBoard[1] &&
                    gameBoard[1] === gameBoard[2]) ||
                (gameBoard[3] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[5] !== 0 &&
                    gameBoard[3] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[5]) ||
                (gameBoard[6] !== 0 &&
                    gameBoard[7] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[6] === gameBoard[7] &&
                    gameBoard[7] === gameBoard[8]) ||
                (gameBoard[0] !== 0 &&
                    gameBoard[3] !== 0 &&
                    gameBoard[6] !== 0 &&
                    gameBoard[0] === gameBoard[3] &&
                    gameBoard[3] === gameBoard[6]) ||
                (gameBoard[1] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[7] !== 0 &&
                    gameBoard[1] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[7]) ||
                (gameBoard[2] !== 0 &&
                    gameBoard[5] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[2] === gameBoard[5] &&
                    gameBoard[5] === gameBoard[8]) ||
                (gameBoard[0] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[0] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[8]) ||
                (gameBoard[2] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[6] !== 0 &&
                    gameBoard[2] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[6])
            ) {
                return Gameboard.lastPlayed();
            }
        },
        // Return winner's name by last play before round termination
        lastPlayed: () => {
            let lastMarker;
            if (markersPlaced % 2 === 0) {
                lastMarker = 2;
            } else {
                lastMarker = 1;
            }
            return lastMarker;
        },
        tieDetector: () => {
            let tieChecker = 0;
            for (let i = 0; i < boardLength; i++) {
                if ((Gameboard.logBoardIndex(i) === 'X') || (Gameboard.logBoardIndex(i) === 'O')) {
                    tieChecker += 1;
                }
            }
            if (tieChecker === 9) {
                console.log("Tie");
            }
        },
        getWinnersName: () => {
            if (Gameboard.lastPlayed() === 1) {
                return player1.getName();
            } else {
                return player2.getName();
            }
        }
    };
})();

// Player object to get name and marker of each player
function Player(playerName, playerMarker) {
    const getName = () => {
        return playerName;
    };
    const getMarker = () => {
        return playerMarker;
    };
    return { getName, getMarker };
}

const Game = (function () {
    return {
        // Start and run the game logic
        start: () => {
            let boardTracker = 0;
            Gameboard.resetBoard();
            while (boardTracker < 9) {
                if (!(Gameboard.checkResults())) {
                    Gameboard.insertMarker(Game.randomValue());
                    if (Gameboard.logBoardIndex(boardTracker) !== 0) {
                        boardTracker += 1;
                    }
                } else if ((Gameboard.checkResults() === 1) || (Gameboard.checkResults() === 2)) {
                    console.log(Game.announceWinner());
                    break;
                }
            }
            if (boardTracker === 9) {
                Gameboard.tieDetector()
            }
            console.log(Gameboard.logBoard());
        },
        // Random number between 0 and 8 to test game logic
        randomValue: () => {
            const randomValue = Math.floor(Math.random() * (8 - 0 + 1)) + 0; // AI-Generated to test functionality
            return randomValue;
        },
        announceWinner: () => {
            return `${Gameboard.getWinnersName()} Won!`;
        }
    };
})();

Game.start();