// Gameboard object for gameboard-related functionality
const Gameboard = (function () {

    // Board variables
    const gameBoard = [];
    const boardLength = 9;
    let markersPlaced = 0;

    // Player variables
    markerX = 'X';
    markerO = 'O';
    let playerOne, playerTwo, playerOnesName, playerTwosName;

    // Marker fields
    const markerFields = document.querySelectorAll('[data-id]');

    function createPlayers() {
        playerOne = Player(playerOnesName, markerX);
        playerTwo = Player(playerTwosName, markerO);
    }

    return {
        initiateButtons: () => {
            markerFields.forEach((markerField) => {
                markerField.addEventListener('click', Gameboard.insertMarker);
            });
        },
        extractNames: () => {
            const nameOne = document.querySelector("#p1").value;
            const nameTwo = document.querySelector("#p2").value;
            if (!(nameOne && nameTwo)) {
                alert("Names cannot be empty!");
            } else {
                playerOnesName = nameOne;
                playerTwosName = nameTwo;
                createPlayers();
                startButton.textContent = "Restart";
                Gameboard.initiateButtons()
            }
        },
        // Reset array and fields to be empty and receive new markers
        resetBoard: (h2) => {
            for (let i = 0; i < boardLength; i++) {
                if (!(gameBoard[i] === 0)) {
                    gameBoard[i] = 0;
                }
                markersPlaced = 0;
                markerFields.forEach(markerField => {
                    markerField.textContent = '';
                    markerField.disabled = false;
                })
            }
            if (h2)
                h2.remove();
        },
        // Insert marker based on TicTacToe's rules
        insertMarker: (e) => {

            const currentButton = e.target;
            const currentButtonIndex = e.target.dataset.id;

            const playerOneMarker = playerOne.getMarker();
            const playerTwoMarker = playerTwo.getMarker();

            if (gameBoard[currentButtonIndex] === 0
                && currentButtonIndex < boardLength
                && currentButtonIndex >= 0
            ) {
                if (markersPlaced % 2 === 0
                    && !(currentButton.textContent)) {
                    gameBoard[currentButtonIndex] = playerOneMarker;
                    currentButton.textContent = playerOneMarker;
                } else {
                    gameBoard[currentButtonIndex] = playerTwoMarker;
                    currentButton.textContent = playerTwoMarker;
                }
                markersPlaced += 1;
                if (markersPlaced >= 5)
                    Gameboard.checkResults();
            }
        },
        // Check if there's a winner based on the array fields
        checkResults: () => {
            if ( // Logic by me, conditions generated by AI to fasten code typing.
                (gameBoard[0] !== 0 &&
                    gameBoard[1] !== 0 &&
                    gameBoard[2] !== 0 &&
                    gameBoard[0] === gameBoard[1] &&
                    gameBoard[1] === gameBoard[2]) ||
                (gameBoard[3] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[5] !== 0 &&
                    gameBoard[3] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[5]) ||
                (gameBoard[6] !== 0 &&
                    gameBoard[7] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[6] === gameBoard[7] &&
                    gameBoard[7] === gameBoard[8]) ||
                (gameBoard[0] !== 0 &&
                    gameBoard[3] !== 0 &&
                    gameBoard[6] !== 0 &&
                    gameBoard[0] === gameBoard[3] &&
                    gameBoard[3] === gameBoard[6]) ||
                (gameBoard[1] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[7] !== 0 &&
                    gameBoard[1] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[7]) ||
                (gameBoard[2] !== 0 &&
                    gameBoard[5] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[2] === gameBoard[5] &&
                    gameBoard[5] === gameBoard[8]) ||
                (gameBoard[0] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[0] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[8]) ||
                (gameBoard[2] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[6] !== 0 &&
                    gameBoard[2] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[6])
            ) {
                Game.announceWinner(playerOnesName, playerTwosName);
                markerFields.forEach(markerField => {
                    markerField.disabled = true;
                })
            }
        },
        // Determine winner based on last play
        lastPlayed: () => {
            let lastMarker;
            if (markersPlaced % 2 === 0) {
                lastMarker = 2;
            } else {
                lastMarker = 1;
            }
            return lastMarker;
        },
        getWinner: () => {
            if (Gameboard.lastPlayed() === 1) {
                return 1;
            } else if (Gameboard.lastPlayed() === 2) {
                return 2;
            }

        }
    };
})();

function Player(playerName, playerMarker) {
    const getName = () => {
        return playerName;
    };
    const getMarker = () => {
        return playerMarker;
    };
    return { getName, getMarker };
}

const Game = (function () {

    const header = document.querySelector('header');
    const h2 = document.createElement('h2');

    return {
        // Both start and restart functionality
        initiateGame: () => {
            Gameboard.extractNames();
            Gameboard.resetBoard(h2);
        },
        announceWinner: (playerOnesName, playerTwosName) => {
            if (Gameboard.getWinner() === 1) {
                h2.textContent = `${playerOnesName} Has WON!`;
            } else if (Gameboard.getWinner() === 2) {
                h2.textContent = `${playerTwosName} Has WON!`;
            }
            header.append(h2)
        }
    };
})();

const startButton = document.querySelector('.start-btn');
startButton.addEventListener('click', Game.initiateGame);