// Gameboard object for gameboard-related functionality
const Gameboard = (function () {

    // Board variables
    const gameBoard = [];
    const boardLength = 9;
    let markersPlaced = 0;

    // Player related variables
    markerX= 'X';
    markerO= 'O';
    let playerOne, playerTwo, playerOnesName, playerTwosName;

    function createPlayers() {
        playerOne = Player(playerOnesName, markerX);
        playerTwo = Player(playerTwosName, markerO);
    }
    return {
        // Reset all values in array from undefined to 0
        extractNames: () => {
            const nameOne= document.querySelector("#p1").value;
            const nameTwo= document.querySelector("#p2").value;
            if (!(nameOne && nameTwo)) {
                alert("Name cannot be empty!");
            } else {
                playerOnesName = nameOne;
                playerTwosName = nameTwo;
                createPlayers();
                startButton.disabled = true;
            }
        },
        resetBoard: () => {
            for (let i = 0; i < boardLength; i++) {
                if (!(gameBoard[i] === 0)) {
                    gameBoard[i] = 0;
                }
            }
        },
        // Log board values 3x3
        logBoard: () => {
            let outputValue = "";
            for (let i = 0; i < boardLength; i++) {
                outputValue += ` ${gameBoard[i]} `;
                if (i === 2 || i === 5 || i === 8) {
                    outputValue += "\n";
                }
            }
            console.log(outputValue);
        },
        // Log specific board index to prevent undefined values
        logBoardIndex: (boardIndex) => {
            const boardValue = gameBoard[boardIndex];
            return boardValue;
        },
        // Logic to insert marker in array, array termination, and array iteration with edge cases
        insertMarker: (index) => {
            const playerOneMarker = playerOne.getMarker();
            const playerTwoMarker = playerTwo.getMarker();

            if (gameBoard[index] === 0 && index < boardLength && index >= 0) {
                if (markersPlaced % 2 === 0) {
                    gameBoard[index] = playerOneMarker;
                } else {
                    gameBoard[index] = playerTwoMarker;
                }
                markersPlaced += 1;
            }
        },
        checkResults: () => {
            if ( // Logic by me, conditions generated by AI to fasten code typing.
                (gameBoard[0] !== 0 &&
                    gameBoard[1] !== 0 &&
                    gameBoard[2] !== 0 &&
                    gameBoard[0] === gameBoard[1] &&
                    gameBoard[1] === gameBoard[2]) ||
                (gameBoard[3] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[5] !== 0 &&
                    gameBoard[3] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[5]) ||
                (gameBoard[6] !== 0 &&
                    gameBoard[7] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[6] === gameBoard[7] &&
                    gameBoard[7] === gameBoard[8]) ||
                (gameBoard[0] !== 0 &&
                    gameBoard[3] !== 0 &&
                    gameBoard[6] !== 0 &&
                    gameBoard[0] === gameBoard[3] &&
                    gameBoard[3] === gameBoard[6]) ||
                (gameBoard[1] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[7] !== 0 &&
                    gameBoard[1] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[7]) ||
                (gameBoard[2] !== 0 &&
                    gameBoard[5] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[2] === gameBoard[5] &&
                    gameBoard[5] === gameBoard[8]) ||
                (gameBoard[0] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[8] !== 0 &&
                    gameBoard[0] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[8]) ||
                (gameBoard[2] !== 0 &&
                    gameBoard[4] !== 0 &&
                    gameBoard[6] !== 0 &&
                    gameBoard[2] === gameBoard[4] &&
                    gameBoard[4] === gameBoard[6])
            ) {
                return Gameboard.lastPlayed();
            }
        },
        lastPlayed: () => {
            let lastMarker;
            if (markersPlaced % 2 === 0) {
                lastMarker = 2;
            } else {
                lastMarker = 1;
            }
            return lastMarker;
        },
        tieDetector: () => {
            let tieChecker = 0;
            for (let i = 0; i < boardLength; i++) {
                if ((Gameboard.logBoardIndex(i) === 'X') || (Gameboard.logBoardIndex(i) === 'O')) {
                    tieChecker += 1;
                }
            }
            if (tieChecker === 9)
                console.log("Tie");
        },
        getWinnersName: () => {
            if (Gameboard.lastPlayed() === 1) {
                return player1.getName();
            } else {
                return player2.getName();
            }
        }
    };
})();

function Player(playerName, playerMarker) {
    const getName = () => {
        return playerName;
    };
    const getMarker = () => {
        return playerMarker;
    };
    return { getName, getMarker };
}

const Game = (function () {
    return {
        start: () => {
            let boardTracker = 0;
            Gameboard.resetBoard();
            while (boardTracker < 9) {
                if (!(Gameboard.checkResults())) {
                    Gameboard.insertMarker(Game.randomValue());
                    // Only increment after ensuring 
                    if (Gameboard.logBoardIndex(boardTracker) !== 0) {
                        boardTracker += 1;
                    }
                } else if (Gameboard.checkResults()) {
                    console.log(`${Gameboard.getWinnersName()} Won!`);
                    break;
                }
            }
            if (boardTracker === 9) {
                Gameboard.tieDetector();
            }
            Gameboard.logBoard();
        },
        // Random number between 0 and 8 to test game logic
        randomValue: () => {
            const randomValue = Math.floor(Math.random() * (8 - 0 + 1)) + 0; // AI-Generated to test functionality
            return randomValue;
        }
    };
})();

const startButton= document.querySelector('.start-btn');
startButton.addEventListener('click', Gameboard.extractNames);

